source ~/.alias
source ~/.vim/inputrc

# .bashrc
Red='\e[0;31m'
RED='\e[1;31m'
blue='\e[0;34m'
BLUE='\e[1;34m'
cyan='\e[0;36m'
CYAN='\e[1;36m'
BLACK='\e[0;30m'
GREEN='\e[0;32m'
PURPLE='\e[0;35m'
BROWN='\e[0;33m'
LIGHTGRAY='\e[0;37m'
DARKGRAY='\e[1;30m'
LIGHTBLUE='\e[1;34m'
LIGHTGREEN='\e[1;32m'
LIGHTCYAN='\e[1;36m'
LIGHTRED='\e[1;31m'
LIGHTPURPLE='\e[1;35m'
YELLOW='\e[1;33m'
WHITE='\e[1;37m'
NC='\e[0m'              # No Color


BGCOLOR="\e[47m"
ENDCOLOR="\e[m"
REDCOLOR="\e[0;31m"
PURPALCOLOR="\e[0;35m"
GREENCOLOR="\e[0;32m"
YELLOWCOLOR="\e[0;33m"

PROPNAMECOLOR=${BROWN}
PROPCOLOR=${LIGHTPURPLE}

PATH=$PATH:~/scripts:~/.vim/bin:~/.vim/scripts
export PATH

alias du='du -h'
alias l='ls -CF'
alias la='ls -CFA'
alias ll='ls -l'
alias l1='ls -1F'
alias l1a='ls -1Fa'
alias l.='ls --color=auto -d .?* 2>/dev/null || echo "No hidden files"'
alias ll.='ls --color=auto -ld .?* 2>/dev/null || echo "No hidden files"'
alias lsd='ls -d */'
alias lll='ls -la | less -X'
alias lart='ls -ACFrt'
alias lrt='ls -CFrt'
alias llrt='ls -lFrt'
alias dir='ls -l'
# alias ls='ls -hF --color=tty'
alias mv='mv -i'
alias rm='rm -i'
alias df='df -h'
alias cp='cp -i'
alias ..='af.cd () { cd ../$1; }; af.cd'
alias ...='af.cd () { cd ../../$1; }; af.cd'
alias ....='af.cd () { cd ../../../$1; }; af.cd'
alias .....='af.cd () { cd ../../../../$1; }; af.cd'
alias clr="clear; pwd; ls -lrth"
alias .paths='echo -e ${PATH//:/\\n}'
alias rga='rg -n --color=always --hidden --follow --ignore-case'

# Define this before calling current file into bash
#export PUNIN=''
#export PNE=''
#export NIS_USER=''
#export NIS_SERVE=''

# cygwin
OSName=`uname -o`
if [ "$OSName" = "Cygwin" ]; then
    OSVer=`uname -s`; PROCName=`uname -m`;
    alias install-apt-cyg='lynx -source rawgit.com/transcode-open/apt-cyg/master/apt-cyg > apt-cyg; install apt-cyg /bin '
fi
if [ "$OSName" = "GNU/Linux" ]; then
    OSVer=`uname -s`; PROCName=`uname -m`;
    alias install-apt-cyg='lynx -source rawgit.com/transcode-open/apt-cyg/master/apt-cyg > apt-cyg; install apt-cyg /bin '
fi

if [ -z "$GIT_STATUS_LEVEL" ]; then
    export GIT_STATUS_LEVEL=0
fi


parse_git_branch() {

    if [ "$GIT_STATUS_LEVEL" == "0" ]; then
        return;
    fi

    branch=`git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'`

    if [ -n "$branch" ];
    then
        reponame=`basename $(git config --get remote.origin.url)| sed -e's/.git//g'`

        if [ "$GIT_STATUS_LEVEL" == "1" ]; then
            echo "($reponame @$branch)"
            return;
        fi

        if [ "$GIT_STATUS_LEVEL" == "2" ]; then
            git diff-files --no-ext-diff --quiet > /dev/null
            if [ $? -ne 0 ]; then
                echo "($reponame @$branch*)"
            else
                echo "($reponame @$branch.)"
            fi
            return;
        fi

        tracked=`git status --untracked-files=no --porcelain 2>/dev/null | wc -l | awk '{ print $1; }'`
        untracked=`git status --porcelain 2>/dev/null | wc -l | awk '{ print $1; }'`

        remote_Status="Ok"
        status_origin=`git status origin 2>/dev/null | grep -i "Your branch "`;

        status=`echo $status_origin | awk '{print $4; }'`;
        if [ "$status" == "behind" ]; then
            remote_Status="Pull"
        fi
        if [ "$status" == "ahead" ]; then
            remote_Status="Push"
        fi
        status=`echo $status_origin | awk '{print $6; }'`;
        if [ "$status" == "diverged," ]; then
            remote_Status="Merge"
        fi
        echo "($reponame @$branch T:+$tracked  UT:+$((untracked - tracked)) RS:$remote_Status)"
    fi

}

export TMUX_HOSTNAME=`hostname -s`
changeTmuxWindowsEveryTime() {
   PROMPT_COMMAND='printf "\033k${TMUX_HOSTNAME}\033\\"'
}

function last_three_dir {
    pwd |rev| awk -F / '{print $1,$2,$3}' | rev | sed s_\ _/_g | sed s_//_/_;
}

mcd() { mkdir -p "$1" && cd "$1"; }

bcd() {
    local levels=${1:-0}
    local maxlevel=$((`echo $PWD |sed 's/[^/]//g'|wc -m`-1 ))

    if [ $levels -gt  $maxlevel ];
    then
        levels=$maxlevel;
    fi

    local bcdpath="."
    while ((levels > 0)); do
            bcdpath=$bcdpath"/.."
            let "levels--"
    done
    cd $bcdpath || break
}

# Helper: Get file counts efficiently (avoids duplicate ls calls)
_prompt_file_counts() {
    local all_count=$(ls -A 2>/dev/null | wc -l | tr -d ' ')
    local visible_count=$(ls 2>/dev/null | wc -l | tr -d ' ')
    echo "Files:${all_count} Hdn:$((all_count - visible_count))"
}

CurrDirDepth() {
    echo `pwd | awk -F"/" '{print NF - 1 ; }'`
}

GetGBaseParent() {
    if [ "$GIT_STATUS_LEVEL" == "0" ]; then
        return;
    fi

    local gbase=`git rev-parse --show-toplevel 2>/dev/null`;
    local subfolder=
    local parentfolder=
    if [ "$gbase"x != ""x ]; then
        subfolder=`basename $(dirname $gbase)`;
        if [ "$subfolder" != "/" ]; then
            parentfolder=`basename $(dirname $(dirname $gbase))`;
            if [ "$parentfolder" == "/" ]; then
                parentfolder=""
            fi
            echo "<$parentfolder/$subfolder> "
        else
            echo "<$subfolder> "
            #echo ${PROPNAMECOLOR}${BG}gprnt:${PROPCOLOR}${BG}$subfolder${PROPNAMECOLOR}${BG}
        fi
    fi
}

# Single source of truth for TMUX window/pane index
UpdateTmuxWinIdx () {
    export TMUX_WINIDX=""
    if [[ -n "$TMUX" ]]; then
        local win_idx=$(tmux display-message -p '#I')
        local pane_idx=$(tmux display-message -p '#P')
        local total_wins=$(tmux display-message -p '#{session_windows}')
        local total_panes=$(tmux display-message -p '#{window_panes}')
        export TMUX_WINIDX="[${win_idx}w${total_wins}.${pane_idx}p${total_panes}] "
    elif [[ -n "$WINDOW" ]]; then
        export TMUX_WINIDX="[$WINDOW] "
    fi
    echo "$TMUX_WINIDX"
}

# \W basename of current directory
SetShortTrap()
{
   local DOName=""
   export PROMPT_DIRTRIM=3
   UpdateTmuxWinIdx > /dev/null
   trap '_cmd_timer_start; PS1="\n${CYAN}\${EXEC_TIME_DISPLAY}${NC}${PROPNAMECOLOR}${BG}(\$((\! -1)) ${PROPNAMECOLOR}${BG}RC:${RED}${BG}\${?##0}${GREEN}${BG}\${?##[1-9]*}${PROPNAMECOLOR}${BG}) ${PROPNAMECOLOR}${BG}Date:${PROPCOLOR}${BG}\D{%d-%b-%y} \D{%T %Z} ${PROPNAMECOLOR}${BG}Jobs:${PROPCOLOR}${BG}\j${PROPNAMECOLOR}${BG} ${PROPCOLOR}\$(_prompt_file_counts) ${PROPNAMECOLOR}pushd:${PROPCOLOR}$(( $( dirs -v | wc -l ) - 1 )) ${PROPNAMECOLOR}${BG}DskUsg:${PROPCOLOR}${BG}\$([ -f ~/.vim/scripts/rootDiskUsage.sh ] && ~/.vim/scripts/rootDiskUsage.sh || [ -f ~/bin/rootDiskUsage.sh ] && ~/bin/rootDiskUsage.sh)${PROPNAMECOLOR}${BG} ${PROPNAMECOLOR}${BG}Os:${PROPCOLOR}${BG}$OSVer${PROPNAMECOLOR}${BG} ${PURPLE}${BG}\$(GetGBaseParent)${NC}${PROPNAMECOLOR}${COLOR_USER}${BG}${USERNAME}${PROPNAMECOLOR}${BG}@${LIGHTPURPLE}${BG}${HOSTNAME%%.*}${DOName}${PROPNAMECOLOR}${BG}:${PURPLE}${BG}\w${NC} ${BROWN}${BG}\$(parse_git_branch)${NC}\n\${SPECIAL_PRMPT_DATA}\$(UpdateTmuxWinIdx)Cmd$ "' DEBUG
}

SetBasicTrap()
{
   local DOName=""
   export PROMPT_DIRTRIM=3
   UpdateTmuxWinIdx > /dev/null
   trap '_cmd_timer_start; PS1="\n${CYAN}\${EXEC_TIME_DISPLAY}${NC}${PROPNAMECOLOR}${BG}(\$((\! -1)) $(((SHLVL>1))&&echo "SL:$SHLVL ")${PROPNAMECOLOR}${BG}RC:${RED}${BG}\${?##0}${GREEN}${BG}\${?##[1-9]*}${PROPNAMECOLOR}${BG}) ${PROPNAMECOLOR}${BG}Date:${PROPCOLOR}${BG}\D{%d-%b-%y} \D{%T %Z} ${PROPNAMECOLOR}${BG}Os:${PROPCOLOR}${BG}$OSVer${PROPNAMECOLOR}${BG} ${PURPLE}${BG}\$(GetGBaseParent)${NC}${PROPNAMECOLOR}${COLOR_USER}${BG}${USERNAME}${PROPNAMECOLOR}${BG}@${LIGHTPURPLE}${BG}${HOSTNAME%%.*}${DOName}${PROPNAMECOLOR}${BG}:${PURPLE}${BG}\w${NC} ${BROWN}${BG}\$(parse_git_branch)${NC}\n\${SPECIAL_PRMPT_DATA}\$(UpdateTmuxWinIdx)Cmd$ "' DEBUG
}

SetBasicTrap

trimoutput() {
    local MAX_CHARS=`stty size | awk '{ print $2 }'`
    $* | cut -c -$MAX_CHARS
}

myssh ()
{
    ssh -X -Y -o "TCPKeepAlive=yes" -o "ServerAliveInterval=90" -o "ServerAliveCountMax=10" -o "ForwardX11=yes" $1
}

mysshtest ()
{
    echo $1 | grep "@" > /dev/null
    if [ $? -ne 0 ]; then
        echo "Please specify user@host";
        return;
    fi

    ssh -o "BatchMode yes" $1 "ls > /dev/null" > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo "Setting passwordless login";
        ssh -X -Y -o "TCPKeepAlive=yes" -o "ServerAliveInterval=90" -o "ServerAliveCountMax=10" -o "ForwardX11=yes" $1 "mkdir ~/.ssh; echo `cat ~/.ssh/id_rsa.pub` >> ~/.ssh/authorized_keys; chmod 700 ~/.ssh; chmod 644 ~/.ssh/authorized_keys"
        ssh -o "BatchMode yes" $1 "ls > /dev/null" > /dev/null 2>&1
        if [ $? -ne 0 ]; then
            echo "Coping custom bashrc";
            tar cf - -C ~/.vim/ bashrc | ssh -X -Y -o "TCPKeepAlive=yes" -o "ServerAliveInterval=90" -o "ServerAliveCountMax=10" -o "ForwardX11=yes" $1 "tar xf - > /dev/null 2>&1;"
            echo "Logging to bash";
            ssh -X -Y -o "TCPKeepAlive=yes" -o "ServerAliveInterval=90" -o "ServerAliveCountMax=10" -o "ForwardX11=yes" -t $1 "bash --rcfile ~/bashrc -i;"
        else
            echo "Coping custom bashrc";
            tar cf - -C ~/.vim bashrc | ssh -X -Y -o "TCPKeepAlive=yes" -o "ServerAliveInterval=90" -o "ServerAliveCountMax=10" -o "BatchMode yes"  -o "ForwardX11=yes" $1 "tar xf - > /dev/null 2>&1;"
            echo "Logging to bash";
            ssh -X -Y -o "TCPKeepAlive=yes" -o "ServerAliveInterval=90" -o "ServerAliveCountMax=10" -o "ForwardX11=yes" -o "BatchMode yes" -t $1 "bash --rcfile ~/bashrc -i;"
        fi
    else
        echo "Coping custom bashrc";
        tar cf - -C ~/.vim bashrc | ssh -X -Y -o "TCPKeepAlive=yes" -o "ServerAliveInterval=90" -o "ServerAliveCountMax=10" -o "BatchMode yes"  -o "ForwardX11=yes" $1 "tar xf - > /dev/null 2>&1;"
        echo "Logging to bash";
        tmux rename-window "$(echo $* | cut -d @ -f2)"
        ssh -X -Y -o "TCPKeepAlive=yes" -o "ServerAliveInterval=90" -o "ServerAliveCountMax=10" -o "ForwardX11=yes" -o "BatchMode yes" -t $1 "bash --rcfile ~/.bashrc -i;"
    fi
}

mysshcftatuld ()
{
    mysshtest atuld@pcft-vm${1}.$PUNIN
}

mysshcft ()
{
    echo $1 | egrep "[0-9]*" > /dev/null
    if [ $? -ne 0 ]; then
        return;
    fi
    mysshtest root@pcft-vm${1}.$PUNIN
}

mysshcftpneatuld ()
{
    mysshtest atuld@pcft-vm${1}.$PNE
}

mysshcftpne ()
{
    echo $1 | egrep "[0-9]*" > /dev/null
    if [ $? -ne 0 ]; then
        return;
    fi
    mysshtest root@pcft-vm${1}.$PNE
}

mysshpass ()
{
    echo "Coping custom bashrc";
    tar cf - -C ~/.vim bashrc | sshpass -f ~/.stdpass ssh -X -Y -o "TCPKeepAlive=yes" -o "ServerAliveInterval=90" -o "ServerAliveCountMax=10" -o "BatchMode yes" -o "ForwardX11=yes" $1 "tar xf - > /dev/null 2>&1;";
    echo "Logging to bash";
    sshpass -f ~/.stdpass ssh -X -Y -o "TCPKeepAlive=yes" -o "ServerAliveInterval=90" -o "ServerAliveCountMax=10" -o "ForwardX11=yes" -o "BatchMode yes" -t $1 "bash --rcfile ~/bashrc -i;"
}

mcd() { mkdir -p "$1" && cd "$1"; }
##########################
# tmux functions start
##########################

# Split pane vertical (right) and run command
tx.v() { tmux split-window -dh "$*"; }

# Split pane horizontal (below) and run command
tx.h() { tmux split-window -dv "$*"; }

# Split vertical and jump to new pane
tx.vj() { tmux split-window -h "$*"; }

# Split horizontal and jump to new pane
tx.hj() { tmux split-window -v "$*"; }

# New window and jump to it
tx.wj() {
    if [[ -n "$*" ]]; then
        tmux new-window "$*; exec $SHELL"
    else
        tmux new-window
    fi
}

# New window, run command, close when done
tx.w() { tmux new-window "$*"; }

# Split vertical and show man page
tx.vman() { tmux split-window -dh "man $*"; }

# Split horizontal and show man page
tx.hman() { tmux split-window -dv "man $*"; }

# Split vertical with readonly viewer (bat or less)
tx.vw() {
    local file="$1"
    [[ -z "$file" ]] && { echo "Usage: tx.vw <file>"; return 1; }
    if command -v bat &>/dev/null; then
        tmux split-window -dh "bat --style=header,numbers,grid,changes --color=always --paging=always --tabs=4 --wrap=auto '$file'"
    else
        tmux split-window -dh "less -i -g -J -N -F -R -S -M -W -Q --mouse '$file'"
    fi
}

# Remote tmux session
tx.remote() {
    local SID=$(tty | cut -d'/' -f4)
    [[ "$1" =~ ^[0-9]+$ ]] && SID=$1
    if [[ "$1" == "ls" ]]; then
        CMD="tmux ls"
    else
        CMD="tmux attach -d -t tmux_$SID || tmux new -s tmux_$SID"
    fi
    ssh -X -Y -o "TCPKeepAlive=yes" -o "ServerAliveInterval=90" -o "ServerAliveCountMax=10" -o "ForwardX11=yes" -t $NIS_USER@$NIS_SERVER $CMD
}

# Remote screen session
tx.scr() {
    local SID=$(tty | cut -d'/' -f4)
    [[ "$1" =~ ^[0-9]+$ ]] && SID=$1
    if [[ "$1" == "ls" ]]; then
        CMD="screen -ls"
    else
        CMD="screen -d -R tmux_$SID"
    fi
    ssh -X -Y -o "TCPKeepAlive=yes" -o "ServerAliveInterval=90" -o "ServerAliveCountMax=10" -o "ForwardX11=yes" -t $NIS_USER@$NIS_SERVER $CMD
}

# ── Modern tmux popup features ──────────────────────────────────────────────

# Generic popup - run any command in a popup window
tx.popup() {
    local cmd="${*:-$SHELL}"
    tmux display-popup -E -w 80% -h 70% -d "#{pane_current_path}" "$cmd"
}

# FZF file picker in popup
tx.fzf() {
    tmux display-popup -E -w 80% -h 70% -d "#{pane_current_path}" \
        'file=$(fzf --preview "cat {}") && [ -n "$file" ] && ${EDITOR:-vim} "$file"'
}

# htop in popup
tx.htop() { tmux display-popup -E -w 90% -h 80% "htop"; }

# lazygit in popup
tx.lazygit() {
    command -v lazygit &>/dev/null && tmux display-popup -E -w 90% -h 90% -d "#{pane_current_path}" "lazygit" || echo "lazygit not installed"
}

# Quick scratch terminal popup
tx.pad() { tmux display-popup -E -w 60% -h 50% -d "#{pane_current_path}" "$SHELL"; }

# Run command in popup and wait
tx.run() { tmux display-popup -E -w 80% -h 70% -d "#{pane_current_path}" "$*; echo; read -n 1 -s -r -p 'Press any key'"; }

# Tail logs in popup
tx.logs() { tmux display-popup -E -w 90% -h 80% "tail -f ${1:-/var/log/system.log}"; }

# List tx commands
tx.help() { echo "tx.v tx.h tx.vj tx.hj tx.w tx.wj tx.vman tx.hman tx.vw tx.remote tx.scr tx.popup tx.fzf tx.htop tx.lazygit tx.pad tx.run tx.logs"; }

##########################
# tmux functions end
##########################


##########################
# git funtions start
##########################
function gfuncdiff() {
    for f in  `git diff --name-only $1`; do git diff $1 $f; done
}

function gstashclone () {
    if [ "$1" == "" ]; then
        echo "Error: Argument expected.."
    else
        git clone ${USER_STASH_URL}
    fi
}

##########################
# git funtions end
##########################

if [ -f /usr/bin/banner ]; then banner "wel-come" && banner "$USER"; fi

##########################
# ENHANCEMENTS START
##########################

# --- Timezone shortcuts ---
alias tz.ist='TZ="Asia/Kolkata" date +"%Y-%m-%d %H:%M:%S %Z"'
alias tz.utc='TZ="UTC" date +"%Y-%m-%d %H:%M:%S %Z"'
alias tz.pst='TZ="America/Los_Angeles" date +"%Y-%m-%d %H:%M:%S %Z"'
alias tz.est='TZ="America/New_York" date +"%Y-%m-%d %H:%M:%S %Z"'
alias tz.cst='TZ="America/Chicago" date +"%Y-%m-%d %H:%M:%S %Z"'
alias tz.all='echo "Local: $(date +"%Y-%m-%d %H:%M:%S %Z")"; echo "UTC:   $(TZ=UTC date +"%Y-%m-%d %H:%M:%S %Z")"; echo "IST:   $(TZ=Asia/Kolkata date +"%Y-%m-%d %H:%M:%S %Z")"; echo "PST:   $(TZ=America/Los_Angeles date +"%Y-%m-%d %H:%M:%S %Z")"'

# --- SSH Agent Management ---
_start_ssh_agent() {
    if [[ -z "$SSH_AUTH_SOCK" ]] || ! ssh-add -l &>/dev/null; then
        local agent_file="$HOME/.ssh/agent.env"
        if [[ -f "$agent_file" ]]; then
            source "$agent_file" &>/dev/null
        fi
        if ! ssh-add -l &>/dev/null; then
            eval "$(ssh-agent -s)" > /dev/null
            echo "export SSH_AUTH_SOCK=$SSH_AUTH_SOCK" > "$agent_file"
            echo "export SSH_AGENT_PID=$SSH_AGENT_PID" >> "$agent_file"
            chmod 600 "$agent_file"
            [[ -f ~/.ssh/id_rsa ]] && ssh-add ~/.ssh/id_rsa 2>/dev/null
            [[ -f ~/.ssh/id_ed25519 ]] && ssh-add ~/.ssh/id_ed25519 2>/dev/null
        fi
    fi
}
[[ $- == *i* ]] && _start_ssh_agent
alias ssh.keys='ssh-add -l'
alias ssh.add='ssh-add'

# --- FZF Keybindings ---
if [[ -f ~/.fzf.bash ]]; then
    source ~/.fzf.bash
elif [[ -f /usr/share/fzf/key-bindings.bash ]]; then
    source /usr/share/fzf/key-bindings.bash
    source /usr/share/fzf/completion.bash 2>/dev/null
elif [[ -f /opt/homebrew/opt/fzf/shell/key-bindings.bash ]]; then
    source /opt/homebrew/opt/fzf/shell/key-bindings.bash
    source /opt/homebrew/opt/fzf/shell/completion.bash 2>/dev/null
elif [[ -f /usr/local/opt/fzf/shell/key-bindings.bash ]]; then
    source /usr/local/opt/fzf/shell/key-bindings.bash
    source /usr/local/opt/fzf/shell/completion.bash 2>/dev/null
fi
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'
export FZF_CTRL_R_OPTS='--sort --exact'

# --- Directory Bookmarks ---
export DIRMARKS_DIR="$HOME/.dirmarks"
[[ -d "$DIRMARKS_DIR" ]] || mkdir -p "$DIRMARKS_DIR"

mark() {
    local name="${1:-$(basename "$PWD")}"
    ln -sfn "$PWD" "$DIRMARKS_DIR/$name"
    echo "Bookmarked: $name -> $PWD"
}

jump() {
    local target="$DIRMARKS_DIR/$1"
    if [[ -L "$target" ]]; then
        cd -P "$target" || return 1
    else
        echo "Bookmark not found: $1"
        marks
        return 1
    fi
}

marks() {
    echo "Directory bookmarks:"
    for f in "$DIRMARKS_DIR"/*; do
        [[ -L "$f" ]] && printf "  %-15s -> %s\n" "$(basename "$f")" "$(readlink "$f")"
    done
}

unmark() {
    if [[ -L "$DIRMARKS_DIR/$1" ]]; then
        rm "$DIRMARKS_DIR/$1"
        echo "Removed bookmark: $1"
    else
        echo "Bookmark not found: $1"
    fi
}

_dirmarks_complete() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    COMPREPLY=($(compgen -W "$(ls "$DIRMARKS_DIR" 2>/dev/null)" -- "$cur"))
}
complete -F _dirmarks_complete jump unmark

# --- Command Execution Time ---
_cmd_timer_start() {
    _cmd_start_time=${_cmd_start_time:-$SECONDS}
}

_cmd_timer_stop() {
    local elapsed=$((SECONDS - ${_cmd_start_time:-$SECONDS}))
    unset _cmd_start_time
    if [[ $elapsed -ge 12 ]]; then
        if [[ $elapsed -ge 3600 ]]; then
            _last_cmd_time="$(($elapsed/3600))h$((($elapsed%3600)/60))m$(($elapsed%60))s"
        elif [[ $elapsed -ge 60 ]]; then
            _last_cmd_time="$(($elapsed/60))m$(($elapsed%60))s"
        else
            _last_cmd_time="${elapsed}s"
        fi
        export EXEC_TIME_DISPLAY="⏱ ${_last_cmd_time} "
    else
        export EXEC_TIME_DISPLAY=""
    fi
}

# Set PROMPT_COMMAND for timer stop (timer start is integrated into Set*Trap functions)
PROMPT_COMMAND="_cmd_timer_stop${PROMPT_COMMAND:+; $PROMPT_COMMAND}"

# --- Kubernetes Context ---
_k8s_context() {
    if command -v kubectl &>/dev/null && [[ -f ~/.kube/config ]]; then
        local ctx ns
        ctx=$(kubectl config current-context 2>/dev/null)
        if [[ -n "$ctx" ]]; then
            ns=$(kubectl config view --minify --output 'jsonpath={..namespace}' 2>/dev/null)
            echo "⎈ ${ctx}/${ns:-default} "
        fi
    fi
}

if command -v kubectl &>/dev/null; then
    alias k='kubectl'
    alias kgp='kubectl get pods'
    alias kgs='kubectl get svc'
    alias kgn='kubectl get nodes'
    alias kga='kubectl get all'
    alias kctx='kubectl config get-contexts'
    alias kns='kubectl config set-context --current --namespace'
    alias klog='kubectl logs -f'
    alias kexec='kubectl exec -it'
fi

##########################
# ENHANCEMENTS END
##########################

myhelp () {
echo "Below are the alias and functions you have"
echo "********************"
echo "********************"
alias
echo "********************"
echo function name
echo "   bcd # == back to # no dir"
echo "   mcd <path> == create dirs and cd to newly creared dir"
echo "   mark [name] == bookmark current directory"
echo "   jump <name> == jump to bookmarked directory"
echo "   marks == list all bookmarks"
echo "   tz.ist/tz.utc/tz.pst/tz.all == timezone shortcuts"
echo "********************"
declare -F
echo "********************"
}
