@REM @SET ALIAS_FOR_ADV_ON=1
@REM @SET ALIAS_FOR_BLD_ON=1
@REM @SET ALIAS_FOR_NBU_ON=1
@REM @SET ALIAS_FOR_SF_ON=1
@REM @SET ALIAS_FOR_PS_ON=1

@REM @SET CFG_EDITOR=vim/gvim/type/notepad
@REM @SET CYGPATH=C:\cygwin64
@REM @SET PERLPATH=C:\Strawberry\perl
@REM @SET VIMPASS=

@REM @SET OPEN_CMD=explorer/start
@REM @SET SPECIAL_PRMPT_DATA=T$S
@REM @SET USE_IP_IN_PROMPT=1

@REM @SET GIT_USER=
@REM @SET GIT_SERVER=
@REM @SET GIT_STATUS_LEVEL=0/1/2/3
@REM @SET GIT_CMD_USED=

