@ECHO OFF
@call gvimdiff -n --cmd "set key=%VIMPASS%" "%USERPROFILE%"\.vim\doc\android_mobile_app_noets.txt "%USERPROFILE%\Dropbox\Worknotes\android_mobile_app_noets.txt"
@call gvimdiff -n --cmd "set key=%VIMPASS%" "%USERPROFILE%"\.vim\doc\Bash.KB.shrtcuts.txt "%USERPROFILE%\Dropbox\Worknotes\Bash KB shrtcuts.txt"
@call gvimdiff -n --cmd "set key=%VIMPASS%" "%USERPROFILE%"\.vim\doc\CmdScriptsCollection.txt "%USERPROFILE%\Dropbox\Worknotes\CmdScriptsCollection.txt"
@call gvimdiff -n --cmd "set key=%VIMPASS%" "%USERPROFILE%"\.vim\doc\ctag-cscope.txt "%USERPROFILE%\Dropbox\Worknotes\ctag-cscope.txt"
@call gvimdiff -n --cmd "set key=%VIMPASS%" "%USERPROFILE%"\.vim\doc\eclipse_notes.txt "%USERPROFILE%\Dropbox\Worknotes\eclipse_notes.txt"
@call gvimdiff -n --cmd "set key=%VIMPASS%" "%USERPROFILE%"\.vim\doc\GeneralNotes.txt "%USERPROFILE%\Dropbox\Worknotes\GeneralNotes.txt"
@call gvimdiff -n --cmd "set key=%VIMPASS%" "%USERPROFILE%"\.vim\doc\Git_help.txt "%USERPROFILE%\Dropbox\Worknotes\Git_help.txt"
@call gvimdiff -n --cmd "set key=%VIMPASS%" "%USERPROFILE%"\.vim\doc\LearningNotes.txt "%USERPROFILE%\Dropbox\Worknotes\LearningNotes.txt"
@call gvimdiff -n --cmd "set key=%VIMPASS%" "%USERPROFILE%"\.vim\doc\MAC.notes.txt "%USERPROFILE%\Dropbox\Worknotes\MAC notes.txt"
@call gvimdiff -n --cmd "set key=%VIMPASS%" "%USERPROFILE%"\.vim\doc\NanoKeyShortcuts.txt "%USERPROFILE%\Dropbox\Worknotes\NanoKeyShortcuts.txt"
@call gvimdiff -n --cmd "set key=%VIMPASS%" "%USERPROFILE%"\.vim\doc\screen.txt "%USERPROFILE%\Dropbox\Worknotes\screen.txt"
@call gvimdiff -n --cmd "set key=%VIMPASS%" "%USERPROFILE%"\.vim\doc\screenrc.txt "%USERPROFILE%\Dropbox\Worknotes\screenrc.txt"
@call gvimdiff -n --cmd "set key=%VIMPASS%" "%USERPROFILE%"\.vim\doc\Tmux.txt "%USERPROFILE%\Dropbox\Worknotes\Tmux.txt"
@call gvimdiff -n --cmd "set key=%VIMPASS%" "%USERPROFILE%"\.vim\doc\toolsQuickRefs.txt "%USERPROFILE%\Dropbox\Worknotes\toolsQuickRefs.txt"
@call gvimdiff -n --cmd "set key=%VIMPASS%" "%USERPROFILE%"\.vim\doc\UnixInGeneral.txt "%USERPROFILE%\Dropbox\Worknotes\UnixInGeneral.txt"
@call gvimdiff -n --cmd "set key=%VIMPASS%" "%USERPROFILE%"\.vim\doc\vi.shortcuts.info_enc.txt "%USERPROFILE%\Dropbox\Worknotes\VI shortcuts info.txt"
@call gvimdiff -n --cmd "set key=%VIMPASS%" "%USERPROFILE%"\.vim\doc\WindowsInGeneral.txt "%USERPROFILE%\Dropbox\Worknotes\WindowsInGeneral.txt"
