@ECHO OFF

@IF "%1" == "QUICK_ACCESS" GOTO QA_ALIAS_DEFINE_INSTALLPATH_MACRO

@IF NOT DEFINED PSTN_MOUNT_DRIVE @SET PSTN_MOUNT_DRIVE=N:

@IF "%1" == "" GOTO DEFINE_MACROS

@SETLOCAL enabledelayedexpansion

@SET VER_ID[80]=8.0
@SET VER_ID[81]=8.1
@SET VER_ID[811]=8.1.1
@SET VER_ID[812]=8.1.2
@SET VER_ID[8121]=8.1.2.1
@SET VER_ID[82]=8.2
@SET VER_ID[83]=8.3
@SET VER_ID[8301]=8.3.0.1
@SET VER_ID[8302]=8.3.0.2
@SET VER_ID[90]=9.0
@SET VER_ID[9001]=9.0.0.1
@SET VER_ID[91]=9.1
@SET VER_ID[9101]=9.1.0.1
@SET VER_ID[912]=9.1.2
@SET VER_ID[0]=0

@SET BLD_ID[80]=0165
@SET BLD_ID[81]=0049
@SET BLD_ID[811]=0103
@SET BLD_ID[812]=0106
@SET BLD_ID[8121]=0016
@SET BLD_ID[82]=0149
@SET BLD_ID[83]=0102
@SET BLD_ID[8301]=0042
@SET BLD_ID[8302]=
@SET BLD_ID[90]=0053
@SET BLD_ID[9001]=0030
@SET BLD_ID[91]=0043
@SET BLD_ID[9101]=
@SET BLD_ID[912]=
@SET BLD_ID[0]=0000

@IF "%1" == "" GOTO END_SCRIPT

@IF "%1" == "LAUNCH" GOTO LAUNCH_SETTING
@IF "%1" == "ECHO" GOTO ECHO_SETTING

:LAUNCH_SETTING
@SET ID=%2
@SET TYPE=%3
@IF "!VER_ID[%ID%]!" == "" @SET "ID=0" && @SET "VER_ID[0]=%2" && @SET "BLD_ID[0]=%3" && @SET TYPE=%4

@SET ARGUMENT=x64\SETUP.EXE %TYPE%
@IF "%ID%" == "80" (
	@IF "%TYPE%" == "/SERVER" ( @SET ARGUMENT=x64\SETUP.EXE ) ELSE ( @SET ARGUMENT=PC_clnt\x64\SETUP.EXE )
)
@IF "%ID%" == "81" (
	@IF "%TYPE%" == "/SERVER" ( @SET ARGUMENT=x64\SETUP.EXE ) ELSE ( @SET ARGUMENT=PC_clnt\x64\SETUP.EXE )
)
GOTO MAIN_LOOP

:ECHO_SETTING
@SET ID=%2
@IF "!VER_ID[%ID%]!" == "" @SET "ID=0" && @SET "VER_ID[0]=%2" && @SET "BLD_ID[0]=%3"
GOTO MAIN_LOOP

:MAIN_LOOP
@SET "BUILD_PATH=%PSTN_MOUNT_DRIVE%\NB\!VER_ID[%ID%]!\NB_!VER_ID[%ID%]!_!BLD_ID[%ID%]!\NetBackup_!VER_ID[%ID%]!_Win"

@IF "%1" == "ECHO" @ECHO %BUILD_PATH%& GOTO END_SCRIPT

START %BUILD_PATH%\%ARGUMENT%

:DEFINE_MACROS
@DOSKEY m.bld.lst..rf=for /F "tokens=*" %%A in ('dir /O /b %PSTN_MOUNT_DRIVE%\NB\$1') do @ECHO %PSTN_MOUNT_DRIVE%\NB\$1\%%A

@DOSKEY m.bld..rs.t=%~dpnx0 LAUNCH $*
@DOSKEY m.bld..rf.b.t=%~dpnx0 LAUNCH $*

@DOSKEY cp.bld..rs=%~dpnx0 ECHO $*^|clip
@DOSKEY cp.bld..rf.b=%~dpnx0 ECHO $*^|clip

:QA_ALIAS_DEFINE_INSTALLPATH_MACRO

:END_SCRIPT


