return {
  "VundleVim/Vundle.vim",
  "tpope/vim-fugitive",
  "vim-scripts/perl-support.vim",
  "vim-scripts/ZoomWin",
  { "ascenator/L9", name = "L9", lazy = true, },
  {
      "nvim-telescope/telescope.nvim",
      dependencies = { "nvim-lua/plenary.nvim" },
      cmd = "Telescope",
      opts = {},
  },

  "vim-scripts/TaskList.vim",
  "sjl/gundo.vim",
  "ervandew/supertab",
  "MattesGroeger/vim-bookmarks",
  "derekwyatt/vim-protodef",
  "mileszs/ack.vim",
  "haya14busa/incsearch.vim",
  "majutsushi/tagbar",
  "vim-scripts/AutoComplPop",
  "vim-scripts/mru.vim",
  "kshenoy/vim-signature",
  "scrooloose/nerdtree",
  "Xuyuanp/nerdtree-git-plugin",
  "tpope/vim-surround",
  "vim-scripts/BufOnly.vim",
  "Lokaltog/vim-powerline",
  "wincent/command-t",
  "vim-scripts/Conque-Shell",
  "kien/ctrlp.vim",
  "Shougo/neocomplcache.vim",
  "vim-scripts/taglist.vim",
  "vim-scripts/Word-Fuzzy-Completion",
  "tpope/vim-pathogen",
  "easymotion/vim-easymotion",
  "xolox/vim-misc",
  "vim-airline/vim-airline",
  "ntpeters/vim-better-whitespace",
  "jez/vim-superman",
  "vim-utils/vim-man",
  "christoomey/vim-tmux-navigator",
  "vim-scripts/a.vim",
  "airblade/vim-gitgutter",
  "elzr/vim-json",
  "othree/html5.vim",
  "godlygeek/tabular",
  "junegunn/vim-easy-align",
  "scrooloose/nerdcommenter",
  "tomtom/tcomment_vim",
  "mbbill/undotree",
  "vim-scripts/YankRing.vim",
  "terryma/vim-multiple-cursors",
  "adinapoli/vim-markmultiple",
  "michaeljsmith/vim-indent-object",
  "gabrielelana/vim-markdown",
  "shime/vim-livedown",
  "vim-scripts/c.vim",
  "Shougo/neocomplete.vim",
  "tpope/vim-eunuch",
  "gregsexton/gitv",
  "mhinz/vim-signify",
  "dhruvasagar/vim-table-mode",
  {
  "xolox/vim-misc",
  lazy = true,
  },
  { "xolox/vim-notes",
   dependencies = { "xolox/vim-misc" },
  },
  "derekwyatt/vim-fswitch",
  "othree/xml.vim",
  "mtth/scratch.vim",
  "Shougo/unite.vim",
  "shougo/vimfiler.vim",
  "andrewradev/linediff.vim",
  "vitalk/vim-simple-todo",
  "tyru/transbuffer.vim",
  "vim-scripts/Lynx-Offline-Documentation-Browser",
  "vim-scripts/bufexplorer.zip",
  "rking/ag.vim",
  "motemen/git-vim",
  "taq/vim-git-branch-info",
  "int3/vim-extradite",
  "junegunn/gv.vim",
  "vim-scripts/git-log",
  "aquach/vim-http-client",
  "chrisbra/vim-diff-enhanced",
  "joonty/vim-do",
  "davidhalter/jedi-vim",
  "junegunn/fzf.vim",
  "mattn/emmet-vim",
  "tibabit/vim-templates",
  "lacombar/vim-mpage",
  "will133/vim-dirdiff",
  "LucHermitte/lh-vim-lib",
  "LucHermitte/lh-vim-lib",
  --{ "LucHermitte/local_vimrc",
  -- dependencies = { "LucHermitte/lh-vim-lib" },
  --},
  "prettier/vim-prettier",
  "bogado/file-line",
  "tpope/vim-abolish",
  "AndrewRadev/tagalong.vim",
  "wavded/vim-stylus",
  "skammer/vim-css-color",
  "digitaltoad/vim-pug",
  "adelarsq/vim-matchit",
  "jelera/vim-javascript-syntax",
  "pangloss/vim-javascript",
  "vim-pandoc/vim-pandoc",
  "thinca/vim-prettyprint",
  "maksimr/vim-jsbeautify"
}
